### ISSUE TITLE
Release Under Free Software License

### ISSUE THREAD

**Issue by thenanobel** [sigsergv/ff-open-reader-view#1]
Hi! I have found your add-on extremely helpful. I see that you have shared the source code on GitHub. I hope that you have shared the source code so that people **have the freedom to run, copy, distribute, study, change and improve** this add-on, which freedoms every [free software](https://www.gnu.org/philosophy/free-sw.html) gives. However even though you intend this, people don't get these freedoms as long as you do not add [licensing information](https://www.gnu.org/licenses/license-list.html#NoLicense) and release your software under a [free software license](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses).

I wish that you intended your software respects users freedom and you would love to release this software under a free software license, for example the GNU General Public License version 3 (GPLv3). Thank you.

**Comment by sigsergv** [comment]
Valid point, thanks. Set GPLv3 explicitly in the code and on the addon page.

**Comment by thenanobel** [comment]
Thank you very much. 💕
